# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: beneficiary.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='beneficiary.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x62\x65neficiary.proto\"R\n\x0b\x62\x65neficiary\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x1b\n\x13\x62\x65neficiary_id_type\x18\x02 \x01(\t\x12\x16\n\x0e\x62\x65neficiary_id\x18\x03 \x01(\t\">\n\x07\x62\x65nData\x12\x1b\n\x13\x62\x65neficiary_id_type\x18\x01 \x01(\t\x12\x16\n\x0e\x62\x65neficiary_id\x18\x02 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BENEFICIARY = _descriptor.Descriptor(
  name='beneficiary',
  full_name='beneficiary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='beneficiary.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beneficiary_id_type', full_name='beneficiary.beneficiary_id_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beneficiary_id', full_name='beneficiary.beneficiary_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=103,
)


_BENDATA = _descriptor.Descriptor(
  name='benData',
  full_name='benData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='beneficiary_id_type', full_name='benData.beneficiary_id_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beneficiary_id', full_name='benData.beneficiary_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=167,
)

DESCRIPTOR.message_types_by_name['beneficiary'] = _BENEFICIARY
DESCRIPTOR.message_types_by_name['benData'] = _BENDATA

beneficiary = _reflection.GeneratedProtocolMessageType('beneficiary', (_message.Message,), dict(
  DESCRIPTOR = _BENEFICIARY,
  __module__ = 'beneficiary_pb2'
  # @@protoc_insertion_point(class_scope:beneficiary)
  ))
_sym_db.RegisterMessage(beneficiary)

benData = _reflection.GeneratedProtocolMessageType('benData', (_message.Message,), dict(
  DESCRIPTOR = _BENDATA,
  __module__ = 'beneficiary_pb2'
  # @@protoc_insertion_point(class_scope:benData)
  ))
_sym_db.RegisterMessage(benData)


# @@protoc_insertion_point(module_scope)
